#!/usr/bin/env python3
"""A MOVE_MATERIAL task's physical work as a validated URML program, lowered to UR.

For mtconnect/cppagent Discussion #615 (making MTConnect's Task model robot-agnostic).

MTConnect's Task model gives a TaskType such as MOVE_MATERIAL: it says WHAT to
accomplish, but not what to do physically. Pinning the physical work to a URScript
File Asset gets you the "what" while re-pinning it to UR, which defeats the
interoperability of the tasks model.

URML's answer: the task references a URML program as its work-to-be-done. The program
is substrate-agnostic (move_to / grasp / release), validated against the cell's
capability manifest and safety envelope, and only then lowered per-robot. For a UR arm
the per-robot adapter emits URScript; on another cell a different adapter emits
something else. The URScript is an adapter output written once, not copied into every
task.

This shows the validate-then-lower shape (mirroring examples/behavior-tree): an
admissible MOVE_MATERIAL program is lowered to an illustrative UR adapter sketch; an
inadmissible one (a machine the cell does not have, a grasp over the gripper cap) is
refused before any URScript is emitted.

Honest altitude: URML validates and carries the structured intent; the per-robot
adapter does the URScript; URML does no motion planning and no control. It contains the
brand-specific layer behind a boundary, it does not make it vanish.

Hermetic and deterministic (the validator only, no MTConnect, no UR, no robot), so the
committed ``move-material-report.txt`` is byte-asserted in CI.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml
from urml_validator import validate

_HERE = Path(__file__).resolve().parent
MANIFEST = _HERE / "three-cnc-cell.manifest.yaml"
_PROFILES = ("industrial",)


def _load(path: Path) -> Any:
    with path.open(encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def _move_material_program(dest: str, grasp_force_n: float) -> dict[str, Any]:
    """The physical work of a MOVE_MATERIAL task: load a blank from infeed into `dest`."""
    return {
        "profile": "industrial",
        "behavior": {
            "type": "sequence",
            "on_error": "abort_and_report",
            "steps": [
                {"move_to": {"location": "infeed_bin"}},
                {"detect": {"object": "blank", "where": {"near": "infeed_bin"}, "store_as": "blank_part"}},
                {"grasp": {"target": "$blank_part", "force": {"newtons": grasp_force_n}}},
                {"move_to": {"location": dest, "carrying": "$blank_part"}},
                {"release": {"mode": "place", "at": dest}},
                {"move_to": {"location": "home_pose"}},
                {
                    "report": {
                        "to": "line_controller",
                        "facts": {"task": "move_material", "from": "infeed_bin", "to": dest},
                        "status": "success",
                    }
                },
            ],
        },
    }


_PROGRAMS = [
    {
        "label": "MOVE_MATERIAL: load a blank into CNC 1",
        "program": _move_material_program("cnc_1_chuck", 40.0),
    },
    {
        "label": "MOVE_MATERIAL: load a blank into CNC 4 (a machine the cell does not have)",
        "program": _move_material_program("cnc_4_chuck", 40.0),
    },
    {
        "label": "MOVE_MATERIAL: load a blank, grasping a heavy billet at 250 N",
        "program": _move_material_program("cnc_2_chuck", 250.0),
    },
]


def _pose_lookup(manifest: dict[str, Any]) -> dict[str, str]:
    out: dict[str, str] = {}
    for loc in manifest["declared_locations"]:
        p = loc["pose"]
        out[loc["name"]] = f"({p['x']:.2f}, {p['y']:.2f}, {p['z']:.2f})"
    return out


def lower_to_urscript(program: dict[str, Any], poses: dict[str, str]) -> list[str]:
    """Lower a validated URML program to an illustrative UR adapter sketch (URScript-flavored).

    Not generated or shipped by URML. A real UR adapter would drive the UR controller
    (RTDE / the UR ROS driver). This shows where the per-robot, brand-specific lowering
    lives, and that it runs only on a program URML already validated.
    """
    out = [
        "    Illustrative UR adapter output (URScript-flavored; NOT generated by URML):",
    ]
    for step in program["behavior"]["steps"]:
        verb, args = next(iter(step.items()))
        args = args or {}
        if verb == "move_to":
            loc = args["location"]
            tail = ", carrying the part" if "carrying" in args else ""
            out.append(f"      movej(pose_{loc})   # -> {poses.get(loc, '<undeclared>')}{tail}")
        elif verb == "detect":
            out.append(f"      # detect: locate {args['object']!r} via wrist_rgb (perception, not a motion)")
        elif verb == "grasp":
            n = args.get("force", {}).get("newtons")
            out.append(f"      rq_close()          # close gripper on the part ({n:.0f} N)")
        elif verb == "release":
            out.append(f"      rq_open()           # release at {args.get('at')}")
        elif verb == "report":
            out.append("      # report task result to line_controller")
    return out


def render_report() -> str:
    manifest = _load(MANIFEST)
    poses = _pose_lookup(manifest)

    lines = [
        "URML: a MOVE_MATERIAL task's physical work as a validated URML program, lowered to UR.",
        "MTConnect's MOVE_MATERIAL TaskType says WHAT to accomplish; the physical work is a URML",
        "program (move_to / grasp / release), validated against the cell manifest + envelope, then",
        "lowered per-robot. An inadmissible program is refused before any URScript is emitted.",
        "For mtconnect/cppagent Discussion #615.",
        "",
        f"cell: {manifest['robot_id']} (one arm tending {sum(1 for loc in manifest['declared_locations'] if loc['name'].startswith('cnc_'))} CNC machines)",
        "",
    ]

    outcomes = []
    for i, p in enumerate(_PROGRAMS, start=1):
        result = validate(p["program"], manifest, profiles=_PROFILES, policy=None)
        codes = sorted({e.code_str for e in result.errors})
        outcomes.append((p["label"], result.accepted, codes))
        lines.append(f"# {i}. {p['label']}")
        lines.append("")
        if result.accepted:
            lines.append("[VALIDATED] the work is admissible on this cell.")
            lines += lower_to_urscript(p["program"], poses)
        else:
            lines.append(f"[REFUSED]   -> {', '.join(codes)}")
            lines.append("   Refused before any URScript is emitted; the invalid work never reaches the UR controller.")
        lines.append("")

    lines += [
        "# Where this fits MTConnect",
        "",
        "A MOVE_MATERIAL task can reference the URML program above as its work-to-be-done,",
        "instead of a UR-pinned URScript File Asset. The program is agnostic and checkable;",
        "the URScript is an adapter output written once per robot family. URML validates and",
        "carries the intent, the UR adapter does the URScript, and URML does no motion planning",
        "and no control. It contains the brand-specific lowering behind a boundary rather than",
        "making it vanish. No dependency on anything of MTConnect's.",
    ]

    # Assert the intended outcomes, so behavior drift fails CI.
    assert outcomes[0][1], "loading a blank into CNC 1 should validate"
    assert not outcomes[1][1], "loading into a machine the cell does not have should be refused"
    assert not outcomes[2][1], "a grasp over the gripper force cap should be refused"

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    out = _HERE / "move-material-report.txt"
    out.write_text(render_report(), encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
