"""The MTConnect MOVE_MATERIAL worked example must be deterministic and true.

Mirrors the urdf-to-manifest / behavior-tree guards: the generator is deterministic,
the committed ``move-material-report.txt`` matches it, an admissible MOVE_MATERIAL
program validates and is lowered, and inadmissible ones (a machine the cell does not
have, a grasp over the gripper cap) are refused before any URScript is emitted. For
mtconnect/cppagent Discussion #615.
"""

from __future__ import annotations

import importlib.util
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
EX = REPO_ROOT / "examples" / "mtconnect-task"
GEN_PATH = EX / "move_material_task.py"
COMMITTED = EX / "move-material-report.txt"


def _load_gen():
    spec = importlib.util.spec_from_file_location("move_material_task", GEN_PATH)
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_generator_is_deterministic() -> None:
    gen = _load_gen()
    assert gen.render_report() == gen.render_report()


def test_committed_report_matches_generator() -> None:
    gen = _load_gen()
    assert COMMITTED.exists(), f"missing {COMMITTED}"
    assert COMMITTED.read_text(encoding="utf-8") == gen.render_report(), (
        "examples/mtconnect-task/move-material-report.txt is stale; "
        "run `python examples/mtconnect-task/move_material_task.py` and commit."
    )


def test_admissible_validates_inadmissible_refused() -> None:
    gen = _load_gen()
    from urml_validator import validate

    manifest = gen._load(gen.MANIFEST)

    ok = validate(gen._move_material_program("cnc_1_chuck", 40.0), manifest, profiles=gen._PROFILES, policy=None)
    assert ok.accepted, "loading a blank into CNC 1 (declared, in-force) should validate"

    bad_prog = gen._move_material_program("cnc_4_chuck", 40.0)
    no_machine = validate(bad_prog, manifest, profiles=gen._PROFILES, policy=None)
    assert not no_machine.accepted, "loading into an undeclared machine should be refused"
    assert "capability.missing_location" in {e.code_str for e in no_machine.errors}

    force_prog = gen._move_material_program("cnc_2_chuck", 250.0)
    over_force = validate(force_prog, manifest, profiles=gen._PROFILES, policy=None)
    assert not over_force.accepted, "a grasp over the 60 N gripper cap should be refused"
    assert "envelope.force_exceeded" in {e.code_str for e in over_force.errors}


def test_report_shows_lowering_and_altitude() -> None:
    gen = _load_gen()
    report = gen.render_report()
    assert "[VALIDATED] the work is admissible on this cell." in report
    assert "Illustrative UR adapter output (URScript-flavored; NOT generated by URML)" in report
    assert "movej(pose_cnc_1_chuck)" in report
    assert "[REFUSED]   -> capability.missing_location" in report
    assert "envelope.force_exceeded" in report
    # Honest altitude line is present.
    assert "does no motion planning" in report
